### ISSUE TITLE
ERROR: Cannot install deep-belief-network and deep-belief-network==1.0.4 because these package versions have conflicting dependencies.

### ISSUE THREAD

**Issue by sheldamohan** [albertbup/deep-belief-network#59]
Hello, Just tried to install this code for my study, but suck with below error. Please help.

ERROR: Cannot install deep-belief-network and deep-belief-network==1.0.4 because these package versions have conflicting dependencies.

The conflict is caused by:
    deep-belief-network 1.0.4 depends on numpy==1.12.0
    scipy 0.18.1 depends on numpy>=1.7.1
    tensorflow 1.5.0 depends on numpy>=1.12.1

**Comment by albertbup** [comment]
Hello,

You're right. Due to version conflicts between packages and also python interpreter version I decided to changed the way you install and use this project. So now the idea is to use a docker image so that no more conflicts between platforms/versions/python appear.

Check the README.md for more details.

Best.
